version: '3'
services:
    nginx:
        image: nginx:1.15
        ports:
            - 80:80
        volumes:
            - .:/usr/share/nginx/html
            - ./tool/nginx/default.conf:/etc/nginx/conf.d/default.conf
